name: Construcción y Despliegue de NestJS con SonarCloud

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: 🧪 Integración Continua (CI)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: 🔍 Analizar con SonarCloud
        uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 'https://sonarcloud.io'
        with:
          args: >
            -Dsonar.organization=eriikjg
            -Dsonar.projectKey=EriikJG_SafeDocsback
            -Dsonar.projectName=SafeDocsback
            -Dsonar.sources=src
            -Dsonar.verbose=true

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  cd:
    name: 🚀 Despliegue Continuo (CD)
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'safedocsback'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
